[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mcat"
version = "0.1.0"
description = "Functions and classes to help at deep learning with PyTorch"
